	char musicRoom_up[] = "             ------ ▲ ------       ";
	char musicRoom_down[] = "             ------ ▼ ------       ";
	char musicRoom_middle[] = "             ----------------       ";//dummy

	char MusicRoom_TH[5][40] = {"   第１弾　東方靈異伝  Arrange ver  ",
								"   第２弾　東方封魔録  Special MIX  ",
								"   第３弾　東方夢時空  Special MIX  ",
								"   第４弾　東方幻想郷  Special MIX  ",
								"   第５弾　東方怪綺談 MysticSquare  " };
	char MUSIC_TITLES[5][30][40] = { {"No.1           A Sacred Lot         ",
									"No.2            永遠の巫女          ",
									"No.3    The Positive and Negative   ",
									"No.4   Highly Responsive to Prayers ",
									"No.5            東方怪奇談          ",
									"No.6             天使伝説           ",
									"No.7        Oriental Magician       ",
									"No.8           破邪の小太刀         ",
									"No.9               魔鏡             ",
									"No.10       the Legend of KAGE      ",
									"No.11    いざ、?れ逝くその時まで   ",
									"No.12      Civilization of Magic    ",
									"No.13            星幽天使           ",
									"No.14            アイリス           ",
									"            タイトルに戻る          ",
									""} ,
								   {"No.1      東方封魔録　～浄土曼荼羅  ",
									"No.2      　 博麗　～Eastern Wind   ",
									"No.3      　  She's in a temper!!   ",
									"No.4      　   End of Daylight　    ",
									"No.5      　  　 やみのちから　　   ",
									"No.6      　　　　　幻夢界　　　　  ",
									"No.7      　　　　死を賭して　　　  ",
									"No.8      ひもろぎ、むらさきにもえ  ",
									"No.9      　  　 恋色マジック 　    ",
									"No.10     　東方封魔録　～幽幻乱舞  ",
									"No.11         Complete Darkness     ",
									"No.12        　 エキストララブ      ",
									"No.13        戦車むすめのみるゆめ   ",
									"No.14          　　遠野の森　　　   ",
									"No.15         昔話わんだーらんど    ",
									"未使用.1         博麗神社境内       ",
									"未使用.2         　陽落ちて  　     ",
									"未使用.3         　封魔終演  　     ",
									"              タイトルに戻る        " },
								   {"No.1       　夢は時空を越えて       ",
									"No.2      　 　 Selection           ",
									"No.3            東方妖恋談          ",
									"No.4          Reincarnation         ",
									"No.5            Dim. Dream          ",
									"No.6     Tabula rasa　～空白少女    ",
									"No.7     　  Maniacal Princess      ",
									"No.8        夢消失  ～Lost Dream    ",
									"No.9       夢幻遊戯  ～Dream War    ",
									"No.10    魔法決戦！～Fight it out!  ",
									"No.11      　 Sailor of Time        ",
									"No.12       Strawberry Crisis!!     ",
									"No.13        非統一魔法世界論       ",
									"No.14          　魔法鐘愛           ",
									"No.15          　久遠の夢           ",
									"No.16          東方の青い空         ",
									"No.17           永遠の満月          ",
									"No.18         Maple Dream...        ",
									"No.19           霊人の休日          ",
									"No.20            勝利デモ           ",
									"No.21         ゲームオーバー        ",
									"未使用.1          時の風            ",
									"未使用.2     スターボウドリーム     ",
									"未使用.3       Phantasmagoria       ",
									"              タイトルに戻る        "},
								   {"No.1    幻想郷  ～ Lotus Land Story ",
									"No.2          Witching Dream        ",
									"No.3          Selene's light        ",
									"No.4   装飾戦　～ Decoration Battle ",
									"No.5         Break the Sabbath      ",
									"No.6    紅響曲  ～ Scarlet Phoneme  ",
									"No.7            Bad Apple!!         ",
									"No.8     霊戦　～ Perdition crisis  ",
									"No.9         アリスマエステラ       ",
									"No.10    少女綺想曲　～ Capriccio   ",
									"No.11   星の器　～ Casket of Star   ",
									"No.12           Lotus Love          ",
									"No.13  眠れる恐怖 ～Sleeping Terror ",
									"No.14           Dream Land          ",
									"No.15    幽夢　～ Inanimate Dream   ",
									"No.16      禁じざるをえない遊戯     ",
									"No.17  メイド幻想　～ Icemilk Magic ",
									"No.18   かわいい悪魔　～ Innocence  ",
									"No.19              Days             ",
									"No.20            Peaceful           ",
									"No.21         Arcadian Dream        ",
									"No.22           幻想の住人          ",
									"未使用.1        Lotus Road          ",
									"未使用.2       Dreamy pilot         ",
									"未使用.3      Incomplete Plot       ",
									"未使用.4        Border Land         ",
									"未使用.5   Magic Shop of Raspberry  ",
									"未使用.6       Crescent Dream       ",
									"              タイトルに戻る        " },
								   {"No.1     怪綺談　～ Mystic Square   ",
									"No.2           Dream Express        ",
									"No.3      魔法陣　～ Magic Square   ",
									"No.4             夢想時空           ",
									"No.5     霊天　～ Spiritual Heaven  ",
									"No.6         Romantic Children      ",
									"No.7       プラスチックマインド     ",
									"No.8          メイプルワイズ        ",
									"No.9  禁断の魔法  ～ Forbidden Magic",
									"No.10  真紅の少女　～ Crimson Dead!!",
									"No.11  裏切りの少女　～ Judas Kiss  ",
									"No.12       the Last Judgement      ",
									"No.13  悲しき人形　～ Doll of Misery",
									"No.14   世界の果て　～ World's End  ",
									"No.15   神話幻想　～ Infinite Being ",
									"No.16       不思議の国のアリス      ",
									"No.17     the Grimoire of Alice     ",
									"No.18              神社             ",
									"No.19            Endless            ",
									"No.20          久遠の楽園           ",
									"No.21         Mystic Dream          ",
									"No.22       Peaceful Romancer       ",
									"No.23         魂の休らむ所          ",
									"              タイトルに戻る        " } };
